export default {
  'pause.svg': '<div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>',
  'text.png': '<a href="https://www.flaticon.com/free-icons/text" title="text icons">Text icons created by Freepik - Flaticon</a>',
  'image.png': '<a href="https://www.flaticon.com/free-icons/picture" title="picture icons">Picture icons created by Freepik - Flaticon</a>',
  'plus.png': '<a href="https://www.flaticon.com/free-icons/plus" title="plus icons">Plus icons created by Freepik - Flaticon</a>',
  'center-align.png': '<a href="https://www.flaticon.com/free-icons/text" title="text icons">Text icons created by Kiranshastry - Flaticon</a>',
  'left-align.png': '<a href="https://www.flaticon.com/free-icons/text" title="text icons">Text icons created by Kiranshastry - Flaticon</a>',
  'right-align.png': '<a href="https://www.flaticon.com/free-icons/alignment" title="alignment icons">Alignment icons created by Kiranshastry - Flaticon</a>',
  'pencil.png': '<a href="https://www.flaticon.com/free-icons/pencil" title="pencil icons">Pencil icons created by tulpahn - Flaticon</a>',
  'link.png': '<a href="https://www.flaticon.com/free-icons/link" title="link icons">Link icons created by alkhalifi design - Flaticon</a>',
  'swap.png': '<a href="https://www.flaticon.com/free-icons/swap" title="swap icons">Swap icons created by Voysla - Flaticon</a>',
  'delete.png': '<a href="https://www.flaticon.com/free-icons/bin" title="bin icons">Bin icons created by Kiranshastry - Flaticon</a>',
  'levels.png': '<a href="https://www.flaticon.com/free-icons/tones" title="tones icons">Tones icons created by Freepik - Flaticon</a>',
  'rows.png': '<a href="https://www.flaticon.com/free-icons/ui" title="ui icons">Ui icons created by Freepik - Flaticon</a>',
  'episode.png': '<a href="https://www.flaticon.com/free-icons/video" title="video icons">Video icons created by Freepik - Flaticon</a>',
  'upload.png': '<a href="https://www.flaticon.com/free-icons/cloud-computing" title="cloud computing icons">Cloud computing icons created by Smartline - Flaticon</a>',
  'forward.png': '<a href="https://www.flaticon.com/free-icons/forward" title="forward icons">Forward icons created by Freepik - Flaticon</a>',
  'history.png': '<a href="https://www.flaticon.com/free-icons/history" title="history icons">History icons created by joalfa - Flaticon</a>',
  'heading.png': '<a href="https://www.flaticon.com/free-icons/heading" title="heading icons">Heading icons created by Royyan Wijaya - Flaticon</a>',
  'eye.png': '<a href="https://www.flaticon.com/free-icons/eye" title="eye icons">Eye icons created by Kiranshastry - Flaticon</a>',
  'eye-slash.png': '<a href="https://www.flaticon.com/free-icons/eye" title="eye icons">Eye icons created by mattbadal - Flaticon</a>'
}